wsgi/openshift/urls.py
from django.conf.urls.defaults import url, patterns, include
from django.contrib import admin
from django.shortcuts import render
from django.views.generic import TemplateView

from haystack.views import SearchView, search_view_factory

from cab import feeds
from cab.forms import AdvancedSearchForm, RegisterForm
from registration.backends.default.views import RegistrationView

admin.autodiscover()


class CabRegistrationView(RegistrationView):
    form_class = RegisterForm


urlpatterns = patterns('',
    url(r'^accounts/', include('allauth.urls')),
    url(r'^accounts/register/$', CabRegistrationView.as_view(),
        name='registration_register'),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^bookmarks/', include('cab.urls.bookmarks')),
    url(r'^comments/', include('django.contrib.comments.urls')),
    url(r'^feeds/author/(?P<username>[\w.@+-]+)/$',
        feeds.SnippetsByAuthorFeed()),
    url(r'^feeds/language/(?P<slug>[\w-]+)/$', feeds.SnippetsByLanguageFeed()),
    url(r'^feeds/latest/$', feeds.LatestSnippetsFeed()),
    url(r'^feeds/tag/(?P<slug>[\w-]+)/$', feeds.SnippetsByTagFeed()),
    url(r'^languages/', include('cab.urls.languages')),
    url(r'^search/$', 'haystack.views.basic_search', name='cab_search'),
    url(r'^search/autocomplete/$', 'cab.views.snippets.autocomplete',
        name='snippet_autocomplete'),
    url(r'^search/advanced/$', search_view_factory(view_class=SearchView,
        template='search/advanced_search.html', form_class=AdvancedSearchForm),
        name='cab_search_advanced'),
    url(r'^recipes/', include('cab.urls.snippets')),
    url(r'^tags/', include('cab.urls.tags')),
    url(r'^users/$', 'cab.views.popular.top_authors', name='cab_top_authors'),
    url(r'^users/(?P<username>[ -_\.\w]+)/$', 'cab.views.snippets.author_snippets',
        name='cab_author_snippets'),
    url(r'^$', lambda request: render(request, 'homepage.html')),
    url(r'^taggit_autosuggest/', include('taggit_autosuggest.urls')),
    url(r'^tos/$', TemplateView.as_view(template_name="tos.html")),                       
    url(r'^about/$', TemplateView.as_view(template_name="about.html")),                       
)

wsgi/openshift/cab/forms.py
from django import forms
from django.contrib import admin

from haystack.forms import SearchForm

from cab.models import Language, Snippet, SnippetFlag, VERSIONS
from registration.forms import RegistrationFormUniqueEmail

from taggit_autosuggest.widgets import TagAutoSuggest
from epiceditor.widgets import AdminEpicEditorWidget
from codemirror.widgets import CodeMirrorTextarea

haskell_textarea = CodeMirrorTextarea(mode="haskell", theme="ambiance", config={ 'fixedGutter': True, 'lineNumbers': False, 'viewportMargin': 5000 })

def validate_non_whitespace_only_string(value):
    """
    Additionally to requiring a non-empty string, this validator also strips
    the string to treat strings with only whitespaces in them as empty.
    """
    if not value or not value.strip():
        raise forms.ValidationError(u'This field is required', code='required')


class SnippetForm(forms.ModelForm):
    title = forms.CharField(
        validators=[validate_non_whitespace_only_string])
    description = forms.CharField(
        validators=[validate_non_whitespace_only_string],
        widget=AdminEpicEditorWidget)
    code = forms.CharField(
        validators=[validate_non_whitespace_only_string],
        widget=haskell_textarea)

    class Meta:
        model = Snippet
        exclude = ('author', 'bookmark_count', 'rating_score', 'version', 'language')


class SnippetFlagForm(forms.ModelForm):
    class Meta:
        model = SnippetFlag
        fields = ('flag',)


class AdvancedSearchForm(SearchForm):
    language = forms.ModelChoiceField(
        queryset=Language.objects.all(), required=False)
    version = forms.MultipleChoiceField(choices=VERSIONS, required=False)
    minimum_pub_date = forms.DateTimeField(
        widget=admin.widgets.AdminDateWidget, required=False)
    minimum_bookmark_count = forms.IntegerField(required=False)
    minimum_rating_score = forms.IntegerField(required=False)

    def search(self):
        # First, store the SearchQuerySet received from other processing.
        sqs = super(AdvancedSearchForm, self).search()

        if not self.is_valid():
            return sqs

        if self.cleaned_data['language']:
            sqs = sqs.filter(language=self.cleaned_data['language'].name)

        if self.cleaned_data['version']:
            sqs = sqs.filter(
                version__in=self.cleaned_data['version'])

        if self.cleaned_data['minimum_pub_date']:
            sqs = sqs.filter(
                pub_date__gte=self.cleaned_data['minimum_pub_date'])

        if self.cleaned_data['minimum_bookmark_count']:
            sqs = sqs.filter(
                bookmark_count__gte=self.cleaned_data['minimum_bookmark_count'])

        if self.cleaned_data['minimum_rating_score']:
            sqs = sqs.filter(
                rating_score__gte=self.cleaned_data['minimum_rating_score'])

        return sqs


class RegisterForm(RegistrationFormUniqueEmail):
    your_name = forms.CharField(label='Your Name', required=False,
                                widget=forms.TextInput(attrs={
                                    'autocomplete': 'off',
                                }))

    def clean(self):
        if self.cleaned_data.get('your_name'):
            raise forms.ValidationError('Please keep the Name field blank')
        return self.cleaned_data

wsgi/openshift/templates/search/advanced_search.html
{% extends 'base.html' %}

{% block title %}Search{% endblock %}

{% block content_header %}Search{% endblock %}

{% block content %}
  <form method="get" action=".">
    <dl>
      <dt><label for="id_q">Search:</dt>
      <dd>{{ form.q }}</dd>
      <dt><label for="id_language">Language:</dt>
      <dd>{{ form.language }}</dd>
      <dt><label for="id_django_version">Django version:</dt>
      <dd>{{ form.django_version }}</dd>
      <dt></dt>
      <dd><input type="submit" value="Search" /></dd>
    </dl>
  </form>
  {% if query %}
    <h3>Results</h3>
    <ul>
    {% for result in page.object_list %}
    <li><a href="{{ result.object.get_absolute_url }}">{{ result.object.title }}</a>, by <a href="/users/{{ result.object.author.username }}/">{{ result.object.author.username }}</a> (user rating: {{ result.object.rating_score }})</li>
    {% empty %}
      <li>No results found.</li>
    {% endfor %}
    </ul>
  {% else %}
    {# pass #}
  {% endif %}
{% endblock %}

wsgi/openshift/templates/search/django_search.html
{% extends 'base.html' %}

{% block title %}Search{% endblock %}

{% block content_header %}Search{% endblock %}

{% block content %}
  <form method="get" action=".">
    <dl>
      <dt><label for="id_q">Search:</dt>
      <dd><input type="text" name="q" id="id_q" value="{{ request.GET.q }}" /></dd>
      <dt></dt>
      <dd><input type="submit" value="Search" /></dd>
    </dl>
  </form>
  {% if query %}
    <h3>Results</h3>
    <ul>
    {% for result in object_list %}
    <li><a href="{{ result.get_absolute_url }}">{{ result.title }}</a>, by <a href="/users/{{ result.author.username }}/">{{ result.author.username }}</a> (user rating: {{ result.rating_score }})</li>
    {% empty %}
      <li>No results found.</li>
    {% endfor %}
    </ul>
  {% else %}
    {# pass #}
  {% endif %}
{% endblock %}

wsgi/openshift/templates/search/search.html
{% extends 'base.html' %}

{% block title %}Search{% endblock %}

{% block content_header %}Search{% endblock %}

{% block content %}
<form method="get" action=".">
  <div class="row collapse">
    <div class="large-8 columns">
      <input type="text" name="q" id="id_q" value="{{ request.GET.q }}" placeholder="Search"/>
    </div>
    <div class="large-4 columns">
      <button class="small" type="submit">Search</button>
    </div>
  </div>
</form>
  {% if query %}
    <h3>Results</h3>
    <ul class="search_results">
    {% for result in page.object_list %}
    <li><a href="{{ result.object.get_absolute_url }}">{{ result.object.title }}</a>, by <a href="/users/{{ result.object.author.username }}/">{{ result.object.author.username }}</a></li>
    {% empty %}
      <li>No results found.</li>
    {% endfor %}
    </ul>
  {% else %}
    {# pass #}
  {% endif %}
{% endblock %}