wsgi/openshift/urls.py
from django.conf.urls.defaults import url, patterns, include
from django.contrib import admin
from django.shortcuts import render
from django.views.generic import TemplateView

from haystack.views import SearchView, search_view_factory

from cab import feeds
from cab.forms import AdvancedSearchForm, RegisterForm
from registration.backends.default.views import RegistrationView

admin.autodiscover()


class CabRegistrationView(RegistrationView):
    form_class = RegisterForm


urlpatterns = patterns('',
    url(r'^accounts/', include('allauth.urls')),
    url(r'^accounts/register/$', CabRegistrationView.as_view(),
        name='registration_register'),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^bookmarks/', include('cab.urls.bookmarks')),
    url(r'^comments/', include('django.contrib.comments.urls')),
    url(r'^feeds/author/(?P<username>[\w.@+-]+)/$',
        feeds.SnippetsByAuthorFeed()),
    url(r'^feeds/language/(?P<slug>[\w-]+)/$', feeds.SnippetsByLanguageFeed()),
    url(r'^feeds/latest/$', feeds.LatestSnippetsFeed()),
    url(r'^feeds/tag/(?P<slug>[\w-]+)/$', feeds.SnippetsByTagFeed()),
    url(r'^languages/', include('cab.urls.languages')),
    url(r'^search/$', 'haystack.views.basic_search', name='cab_search'),
    url(r'^search/autocomplete/$', 'cab.views.snippets.autocomplete',
        name='snippet_autocomplete'),
    url(r'^search/advanced/$', search_view_factory(view_class=SearchView,
        template='search/advanced_search.html', form_class=AdvancedSearchForm),
        name='cab_search_advanced'),
    url(r'^recipes/', include('cab.urls.snippets')),
    url(r'^tags/', include('cab.urls.tags')),
    url(r'^users/$', 'cab.views.popular.top_authors', name='cab_top_authors'),
    url(r'^users/(?P<username>[ -_\.\w]+)/$', 'cab.views.snippets.author_snippets',
        name='cab_author_snippets'),
    url(r'^$', lambda request: render(request, 'homepage.html')),
    url(r'^taggit_autosuggest/', include('taggit_autosuggest.urls')),
    url(r'^tos/$', TemplateView.as_view(template_name="tos.html")),                       
    url(r'^about/$', TemplateView.as_view(template_name="about.html")),                       
)

wsgi/openshift/cab/models.py
from django.contrib.auth.models import User
from django.contrib.comments.moderation import moderator
from django.conf import settings
from django.db import models
from django.db.models import Count, permalink

from comments_spamfighter.moderation import SpamFighterModerator
from ratings.models import Ratings
from taggit_autosuggest.managers import TaggableManager

from markdown import markdown
from pygments import formatters, highlight, lexers


VERSIONS = getattr(settings, 'CAB_VERSIONS', ())


class LanguageManager(models.Manager):
    def top_languages(self):
        return self.annotate(score=Count('snippet')).order_by('-score')


class Language(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    language_code = models.CharField(max_length=50)
    mime_type = models.CharField(max_length=100)
    file_extension = models.CharField(max_length=10)

    objects = LanguageManager()

    class Meta:
        ordering = ('name',)

    def __unicode__(self):
        return self.name

    @permalink
    def get_absolute_url(self):
        return ('cab_language_detail', (), {'slug': self.slug})

    def get_lexer(self):
        return lexers.get_lexer_by_name(self.language_code)


def haskell(): return Language.objects.get(name='Haskell')

class SnippetManager(models.Manager):
    def top_authors(self):
        return User.objects.annotate(
            score=Count('snippet')).order_by('-score', 'username')

    def top_tags(self):
        return self.model.tags.most_common().order_by('-num_times', 'name')

    def top_rated(self):
        # this is slow
        # return self.annotate(score=Sum('ratings__score')).order_by('-score')
        return self.all().order_by('-rating_score', '-pub_date')

    def most_bookmarked(self):
        # this is slow
        # self.annotate(score=Count('bookmarks')).order_by('-score')
        return self.all().order_by('-bookmark_count', '-pub_date')

    def matches_tag(self, tag):
        return self.filter(tags__in=[tag])

    def get_count(self):
        return self.count()


class Snippet(models.Model):
    title = models.CharField(max_length=255)
    language = models.ForeignKey(Language, default=haskell)
    author = models.ForeignKey(User)
    description = models.TextField()
    description_html = models.TextField(editable=False)
    code = models.TextField()
    highlighted_code = models.TextField(editable=False)
    version = models.FloatField(choices=VERSIONS, default=0)
    pub_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    bookmark_count = models.IntegerField(default=0)  # denormalized count
    rating_score = models.IntegerField(default=0)  # denormaliazed score

    ratings = Ratings()
    tags = TaggableManager()

    objects = SnippetManager()

    class Meta:
        ordering = ('-pub_date',)

    def __unicode__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.description_html = markdown(self.description, safe_mode="escape")
        self.highlighted_code = self.highlight()
        super(Snippet, self).save(*args, **kwargs)

    @permalink
    def get_absolute_url(self):
        return ('cab_snippet_detail', (), {'snippet_id': self.id})

    def highlight(self):
        return highlight(self.code,
                         self.language.get_lexer(),
                         formatters.HtmlFormatter(linenos=True))

    def get_tagstring(self):
        return ", ".join([t.name for t in self.tags.order_by('name').all()])

    def get_version(self):
        return dict(VERSIONS)[self.version]

    def update_rating(self):
        self.rating_score = self.ratings.cumulative_score() or 0
        self.save()

    def update_bookmark_count(self):
        self.bookmark_count = self.bookmarks.count() or 0
        self.save()


class SnippetFlag(models.Model):
    FLAG_SPAM = 1
    FLAG_INAPPROPRIATE = 2
    FLAG_CHOICES = (
        (FLAG_SPAM, 'Spam'),
        (FLAG_INAPPROPRIATE, 'Inappropriate'),
    )
    snippet = models.ForeignKey(Snippet, related_name='flags')
    user = models.ForeignKey(User)
    flag = models.IntegerField(choices=FLAG_CHOICES)

    def __unicode__(self):
        return '%s flagged as %s by %s' % (
            self.snippet.title,
            self.get_flag_display(),
            self.user.username,
        )

    def remove_and_ban(self):
        user = self.snippet.author
        user.set_unusable_password()
        user.is_active = False
        user.save()
        self.snippet.delete()


class Bookmark(models.Model):
    snippet = models.ForeignKey(Snippet, related_name='bookmarks')
    user = models.ForeignKey(User, related_name='cab_bookmarks')
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-date',)

    def __unicode__(self):
        return "%s bookmarked by %s" % (self.snippet, self.user)

    def save(self, *args, **kwargs):
        super(Bookmark, self).save(*args, **kwargs)
        self.snippet.update_bookmark_count()

    def delete(self, *args, **kwargs):
        super(Bookmark, self).delete(*args, **kwargs)
        self.snippet.update_bookmark_count()


class SnippetModerator(SpamFighterModerator):
    # Regular options by Django's contributed CommentModerator
    email_notification = True

    # Spam fighter options:
    # Check with Akismet for spam
    akismet_check = True
    # If Akismet marks this message as spam, delete it instantly (False) or
    # add it the comment the moderation queue (True). Default is True.
    akismet_check_moderate = True
    # Do a keyword check
    keyword_check = False
    # If a keyword is found, delete it instantly (False) or add the comment to
    # the moderation queue (True). Default is False.
    keyword_check_moderate = True


moderator.register(Snippet, SnippetModerator)


from cab.listeners import start_listening
start_listening()

wsgi/openshift/cab/comments/forms.py
from django import forms
from django.contrib.comments.forms import CommentForm
from captcha.fields import ReCaptchaField


class CabCommentForm(CommentForm):
    your_name = forms.CharField(label='Your Name', required=False,
                                widget=forms.TextInput(attrs={
                                    'autocomplete': 'off',
                                }))
    captcha = ReCaptchaField(attrs={'theme': 'clean'})

    def clean(self):
        if self.cleaned_data.get('your_name'):
            raise forms.ValidationError('Please keep the Name field blank')
        return self.cleaned_data

wsgi/openshift/templates/comments/comment_posted.html
{% extends "base.html" %}

{% block title %}Comment posted{% endblock %}

{% block content_header %}Comment posted{% endblock %}

{% block content %}
<p>Your comment posted successfully; perhaps you'd like to <a href="{{ object.get_absolute_url }}">go take a look at it</a>?</p>
{% endblock %}

wsgi/openshift/templates/comments/form.html
{% load i18n %}
{% if request.user.is_authenticated %}
<form action="/comments/post/" method="post">{% csrf_token %}

{{ form.non_field_errors }}

<p>{% trans "Username:" %} <strong>{{ user.username }}</strong> (<a href="/accounts/logout/">{% trans "Log out" %}</a>)</p>
<dl>

<div class="bee-like-this">
    {# A honeypot field called "your_name" #}
    <dt><label for="id_your_name">{% trans "Your Name:" %}</label></dt>
    <dd>{{ form.your_name }}</dd>
</div>

<dt><label for="id_comment">{% trans "Comment:" %}</label></dt>
<dd><textarea name="comment" id="id_comment" rows="10" cols="60"></textarea><br />
You may use <a href="http://daringfireball.net/projects/markdown/syntax">Markdown syntax</a> here, but <strong>raw HTML will be removed</strong>.</dd>

<dt>
<div style="display:none;">
    {{ form.honeypot }}
    {{ form.content_type }}
    {{ form.object_pk }}
    {{ form.timestamp }}
    {{ form.security_hash }}
</div>
    <button type="submit" name="preview" class="small" value="{% trans "Preview comment" %}">{% trans "Preview comment" %}</button>
</dt>
</dl>
</form>
{% else %}
<form action="/accounts/login/" method="post">{% csrf_token %}
<dl>
<dt><label for="id_username">{% trans "Username:" %}</label></dt>
<dd><input type="text" name="username" id="id_username" /></dd>
<dt><label for="id_password">{% trans "Password:" %}</label></dt>
<dd><input type="password" name="password" id="id_password" /> (<a href="/accounts/password_reset/">{% trans "Forgotten your password?" %}</a>)</dd>
<dt></dt>
<dd><button type="submit" class="small" value="Login">Login</button></dd>
</dl>
<input type="hidden" name="next" value="{{ request.get_full_path }}" />
</form>
{% endif %}

wsgi/openshift/templates/comments/posted.html
{% extends "base.html" %}

{% block title %}Comment posted{% endblock %}

{% block content_header %}Comment posted{% endblock %}

{% block content %}
<p>Your comment posted successfully; perhaps you'd like to <a href="{{ comment.content_object.get_absolute_url }}#c{{ comment.id }}">go take a look at it</a>?</p>
{% endblock %}

wsgi/openshift/templates/comments/preview.html
{% extends "base.html" %}

{% load i18n %}

{% block title %}Post a comment{% endblock %}

{% block content_header %}Post a comment{% endblock %}

{% block content %}
{% load safe_markup %}
{{ form.non_field_errors }}

<dl>

<div class="bee-like-this">
    {# A honeypot field called "name" #}
    <dt><label for="id_name">{% trans "Your Name:" %}</label></dt>
    <dd>{{ form.name.errors }}{{ form.name }}</dd>
</div>

<form action="/comments/post/" method="post">{% csrf_token %}

<dt><a href="/users/{{ comment.user.username }}/">{{ user.username }}</a></dt>
<dd>{{ comment|safe_markdown:"safe"|safe }}</dd>

<dt><label for="id_comment">Comment:</label></dt>
<dd>{{ form.comment.errors }}{{ form.comment }}</dd>

<dt><label for="id_captcha">{% trans "Captcha:" %}</label></dt>
<dd>{{ form.captcha.errors }}{{ form.captcha }}</dd>

<p>
<input type="submit" name="preview" value="Preview comment" />
<input type="submit" name="post" value="Post comment" />
</p>
<p style="display:none;">
  {{ form.honeypot }}
  {{ form.content_type }}
  {{ form.object_pk }}
  {{ form.timestamp }}
  {{ form.security_hash }}
</p>
</form>
</dl>

{% endblock %}

{% block sidebar %}
<p>Here's what your comment will look like; if you're happy with it, go ahead and post, or feel free to edit and preview again.</p>
<p>Remember that you can use Markdown syntax, but <strong>raw HTML will be removed</strong>.
{% endblock %}