wsgi/openshift/urls.py
from django.conf.urls.defaults import url, patterns, include
from django.contrib import admin
from django.shortcuts import render
from django.views.generic import TemplateView

from haystack.views import SearchView, search_view_factory

from cab import feeds
from cab.forms import AdvancedSearchForm, RegisterForm
from registration.backends.default.views import RegistrationView

admin.autodiscover()


class CabRegistrationView(RegistrationView):
    form_class = RegisterForm


urlpatterns = patterns('',
    url(r'^accounts/', include('allauth.urls')),
    url(r'^accounts/register/$', CabRegistrationView.as_view(),
        name='registration_register'),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^bookmarks/', include('cab.urls.bookmarks')),
    url(r'^comments/', include('django.contrib.comments.urls')),
    url(r'^feeds/author/(?P<username>[\w.@+-]+)/$',
        feeds.SnippetsByAuthorFeed()),
    url(r'^feeds/language/(?P<slug>[\w-]+)/$', feeds.SnippetsByLanguageFeed()),
    url(r'^feeds/latest/$', feeds.LatestSnippetsFeed()),
    url(r'^feeds/tag/(?P<slug>[\w-]+)/$', feeds.SnippetsByTagFeed()),
    url(r'^languages/', include('cab.urls.languages')),
    url(r'^search/$', 'haystack.views.basic_search', name='cab_search'),
    url(r'^search/autocomplete/$', 'cab.views.snippets.autocomplete',
        name='snippet_autocomplete'),
    url(r'^search/advanced/$', search_view_factory(view_class=SearchView,
        template='search/advanced_search.html', form_class=AdvancedSearchForm),
        name='cab_search_advanced'),
    url(r'^recipes/', include('cab.urls.snippets')),
    url(r'^tags/', include('cab.urls.tags')),
    url(r'^users/$', 'cab.views.popular.top_authors', name='cab_top_authors'),
    url(r'^users/(?P<username>[ -_\.\w]+)/$', 'cab.views.snippets.author_snippets',
        name='cab_author_snippets'),
    url(r'^$', lambda request: render(request, 'homepage.html')),
    url(r'^taggit_autosuggest/', include('taggit_autosuggest.urls')),
    url(r'^tos/$', TemplateView.as_view(template_name="tos.html")),                       
    url(r'^about/$', TemplateView.as_view(template_name="about.html")),                       
)

wsgi/openshift/cab/models.py
from django.contrib.auth.models import User
from django.contrib.comments.moderation import moderator
from django.conf import settings
from django.db import models
from django.db.models import Count, permalink

from comments_spamfighter.moderation import SpamFighterModerator
from ratings.models import Ratings
from taggit_autosuggest.managers import TaggableManager

from markdown import markdown
from pygments import formatters, highlight, lexers


VERSIONS = getattr(settings, 'CAB_VERSIONS', ())


class LanguageManager(models.Manager):
    def top_languages(self):
        return self.annotate(score=Count('snippet')).order_by('-score')


class Language(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    language_code = models.CharField(max_length=50)
    mime_type = models.CharField(max_length=100)
    file_extension = models.CharField(max_length=10)

    objects = LanguageManager()

    class Meta:
        ordering = ('name',)

    def __unicode__(self):
        return self.name

    @permalink
    def get_absolute_url(self):
        return ('cab_language_detail', (), {'slug': self.slug})

    def get_lexer(self):
        return lexers.get_lexer_by_name(self.language_code)


def haskell(): return Language.objects.get(name='Haskell')

class SnippetManager(models.Manager):
    def top_authors(self):
        return User.objects.annotate(
            score=Count('snippet')).order_by('-score', 'username')

    def top_tags(self):
        return self.model.tags.most_common().order_by('-num_times', 'name')

    def top_rated(self):
        # this is slow
        # return self.annotate(score=Sum('ratings__score')).order_by('-score')
        return self.all().order_by('-rating_score', '-pub_date')

    def most_bookmarked(self):
        # this is slow
        # self.annotate(score=Count('bookmarks')).order_by('-score')
        return self.all().order_by('-bookmark_count', '-pub_date')

    def matches_tag(self, tag):
        return self.filter(tags__in=[tag])

    def get_count(self):
        return self.count()


class Snippet(models.Model):
    title = models.CharField(max_length=255)
    language = models.ForeignKey(Language, default=haskell)
    author = models.ForeignKey(User)
    description = models.TextField()
    description_html = models.TextField(editable=False)
    code = models.TextField()
    highlighted_code = models.TextField(editable=False)
    version = models.FloatField(choices=VERSIONS, default=0)
    pub_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    bookmark_count = models.IntegerField(default=0)  # denormalized count
    rating_score = models.IntegerField(default=0)  # denormaliazed score

    ratings = Ratings()
    tags = TaggableManager()

    objects = SnippetManager()

    class Meta:
        ordering = ('-pub_date',)

    def __unicode__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.description_html = markdown(self.description, safe_mode="escape")
        self.highlighted_code = self.highlight()
        super(Snippet, self).save(*args, **kwargs)

    @permalink
    def get_absolute_url(self):
        return ('cab_snippet_detail', (), {'snippet_id': self.id})

    def highlight(self):
        return highlight(self.code,
                         self.language.get_lexer(),
                         formatters.HtmlFormatter(linenos=True))

    def get_tagstring(self):
        return ", ".join([t.name for t in self.tags.order_by('name').all()])

    def get_version(self):
        return dict(VERSIONS)[self.version]

    def update_rating(self):
        self.rating_score = self.ratings.cumulative_score() or 0
        self.save()

    def update_bookmark_count(self):
        self.bookmark_count = self.bookmarks.count() or 0
        self.save()


class SnippetFlag(models.Model):
    FLAG_SPAM = 1
    FLAG_INAPPROPRIATE = 2
    FLAG_CHOICES = (
        (FLAG_SPAM, 'Spam'),
        (FLAG_INAPPROPRIATE, 'Inappropriate'),
    )
    snippet = models.ForeignKey(Snippet, related_name='flags')
    user = models.ForeignKey(User)
    flag = models.IntegerField(choices=FLAG_CHOICES)

    def __unicode__(self):
        return '%s flagged as %s by %s' % (
            self.snippet.title,
            self.get_flag_display(),
            self.user.username,
        )

    def remove_and_ban(self):
        user = self.snippet.author
        user.set_unusable_password()
        user.is_active = False
        user.save()
        self.snippet.delete()


class Bookmark(models.Model):
    snippet = models.ForeignKey(Snippet, related_name='bookmarks')
    user = models.ForeignKey(User, related_name='cab_bookmarks')
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-date',)

    def __unicode__(self):
        return "%s bookmarked by %s" % (self.snippet, self.user)

    def save(self, *args, **kwargs):
        super(Bookmark, self).save(*args, **kwargs)
        self.snippet.update_bookmark_count()

    def delete(self, *args, **kwargs):
        super(Bookmark, self).delete(*args, **kwargs)
        self.snippet.update_bookmark_count()


class SnippetModerator(SpamFighterModerator):
    # Regular options by Django's contributed CommentModerator
    email_notification = True

    # Spam fighter options:
    # Check with Akismet for spam
    akismet_check = True
    # If Akismet marks this message as spam, delete it instantly (False) or
    # add it the comment the moderation queue (True). Default is True.
    akismet_check_moderate = True
    # Do a keyword check
    keyword_check = False
    # If a keyword is found, delete it instantly (False) or add the comment to
    # the moderation queue (True). Default is False.
    keyword_check_moderate = True


moderator.register(Snippet, SnippetModerator)


from cab.listeners import start_listening
start_listening()

wsgi/openshift/cab/comments/forms.py
from django import forms
from django.contrib.comments.forms import CommentForm
from captcha.fields import ReCaptchaField


class CabCommentForm(CommentForm):
    your_name = forms.CharField(label='Your Name', required=False,
                                widget=forms.TextInput(attrs={
                                    'autocomplete': 'off',
                                }))
    captcha = ReCaptchaField(attrs={'theme': 'clean'})

    def clean(self):
        if self.cleaned_data.get('your_name'):
            raise forms.ValidationError('Please keep the Name field blank')
        return self.cleaned_data

wsgi/openshift/cab/views/bookmarks.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required

from cab.models import Bookmark, Snippet
from cab.utils import object_list


@login_required
def user_bookmarks(request):
    return object_list(
        request,
        queryset=Bookmark.objects.filter(user__pk=request.user.id),
        template_name='cab/user_bookmarks.html',
        paginate_by=20)


@login_required
def add_bookmark(request, snippet_id):
    # TODO: this should probably be a POST action
    snippet = get_object_or_404(Snippet, pk=snippet_id)
    try:
        Bookmark.objects.get(user=request.user,
                             snippet=snippet)
    except Bookmark.DoesNotExist:
        Bookmark.objects.create(user=request.user,
                                snippet=snippet)
    return redirect(snippet)


@login_required
def delete_bookmark(request, snippet_id):
    bookmark = get_object_or_404(Bookmark,
                                 snippet__pk=snippet_id,
                                 user=request.user)
    if request.method == 'POST':
        bookmark.delete()
        return redirect(bookmark.snippet)
    else:
        return render(request, 'cab/confirm_bookmark_delete.html',
                      {'snippet': bookmark.snippet})

wsgi/openshift/cab/views/languages.py
from django.shortcuts import get_object_or_404

from cab.models import Language
from cab.utils import month_object_list, object_list


def language_list(request):
    return object_list(
        request,
        queryset=Language.objects.all(),
        paginate_by=20,
    )


def language_detail(request, slug):
    language = get_object_or_404(Language, slug=slug)
    return month_object_list(
        request,
        queryset=language.snippet_set.all(),
        paginate_by=20,
        template_name='cab/language_detail.html',
        extra_context={'language': language},
    )

wsgi/openshift/cab/views/popular.py
from cab.models import Snippet, Language
from cab.utils import month_object_list, object_list


def top_authors(request):
    return object_list(
        request,
        queryset=Snippet.objects.top_authors(),
        template_name='cab/top_authors.html',
        paginate_by=20)


def top_languages(request):
    return object_list(
        request,
        queryset=Language.objects.top_languages(),
        template_name='cab/language_list.html',
        paginate_by=20)


def top_tags(request):
    return object_list(
        request,
        queryset=Snippet.objects.top_tags(),
        template_name='cab/tag_list.html',
        paginate_by=20,
    )


def top_bookmarked(request):
    queryset = Snippet.objects.most_bookmarked()
    return month_object_list(
        request,
        queryset=queryset,
        template_name='cab/most_bookmarked.html',
        paginate_by=20,
    )


def top_rated(request):
    queryset = Snippet.objects.top_rated()
    return month_object_list(
        request,
        queryset=queryset,
        template_name='cab/top_rated.html',
        paginate_by=20,
    )

wsgi/openshift/cab/views/snippets.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.mail import mail_admins
from django.core.urlresolvers import reverse
from django.db.models import Q, Count
from django.http import HttpResponseForbidden, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import simplejson as json

from haystack.query import SearchQuerySet

from taggit.models import Tag

from cab.forms import SnippetForm, SnippetFlagForm
from cab.models import Snippet, SnippetFlag, Language, haskell
from cab.utils import month_object_list, object_detail


def snippet_list(request, queryset=None, **kwargs):
    if queryset is None:
        queryset = Snippet.objects.all()

    return month_object_list(
        request,
        queryset=queryset,
        paginate_by=20,
        **kwargs
    )


def snippet_detail(request, snippet_id):
    return object_detail(
        request,
        queryset=Snippet.objects.all(),
        object_id=snippet_id,
        extra_context={'flag_form': SnippetFlagForm()},
    )


def download_snippet(request, snippet_id):
    snippet = get_object_or_404(Snippet, pk=snippet_id)
    response = HttpResponse(snippet.code, mimetype='text/plain')
    response['Content-Disposition'] = 'attachment; filename=%s.%s' % \
        (snippet.id, snippet.language.file_extension)
    response['Content-Type'] = snippet.language.mime_type
    return response


@login_required
def rate_snippet(request, snippet_id):
    snippet = get_object_or_404(Snippet, pk=snippet_id)
    score = request.GET.get('score')
    if score and score in ['up', 'down']:
        score = {'up': 1, 'down': -1}[score]
        snippet.ratings.rate(user=request.user, score=score)
    return redirect(snippet)


@login_required
def edit_snippet(request, snippet_id=None,
                 template_name='cab/edit_snippet.html'):
    if not request.user.is_active:
        return HttpResponseForbidden()

    if snippet_id:
        snippet = get_object_or_404(Snippet, pk=snippet_id)
        if request.user.id != snippet.author.id:
            return HttpResponseForbidden()
    else:
        template_name = 'cab/add_snippet.html'
        snippet = Snippet(author=request.user,
                          language=haskell())

    if request.method == 'POST':
        form = SnippetForm(instance=snippet, data=request.POST)
        if form.is_valid():
            snippet = form.save()
            messages.info(request, 'Your snippet has been saved')
            return redirect(snippet)
    else:
        form = SnippetForm(instance=snippet)

    return render(request, template_name, {'form': form})


@login_required
def flag_snippet(request, snippet_id):
    snippet = get_object_or_404(Snippet, id=snippet_id)
    snippet_flag = SnippetFlag(snippet=snippet, user=request.user)
    form = SnippetFlagForm(request.POST, instance=snippet_flag)

    if form.is_valid():
        snippet_flag = form.save()

        admin_link = request.build_absolute_uri(
            reverse('admin:cab_snippetflag_changelist')
        )

        mail_admins(
            'Snippet flagged: "%s"' % (snippet.title),
            '%s\n\nAdmin link: %s' % (snippet_flag, admin_link),
            fail_silently=True,
        )

        messages.info(request, 'Thank you for helping improve the site!')
    else:
        messages.error(request, 'Invalid form submission')

    return redirect(snippet)


def author_snippets(request, username):
    user = get_object_or_404(User, username=username)
    snippet_qs = Snippet.objects.filter(author=user)
    return snippet_list(
        request,
        snippet_qs,
        template_name='cab/user_detail.html',
        extra_context={'author': user},
    )


def matches_tag(request, slug):
    tag = get_object_or_404(Tag, slug=slug)
    snippet_qs = Snippet.objects.matches_tag(tag)
    return snippet_list(
        request,
        queryset=snippet_qs,
        template_name='cab/tag_detail.html',
        extra_context={'tag': tag},
    )


def search(request):
    query = request.GET.get('q')
    snippet_qs = Snippet.objects.none()
    if query:
        snippet_qs = Snippet.objects.filter(
            Q(title__icontains=query) |
            Q(tags__in=[query]) |
            Q(author__username__iexact=query)
        ).distinct().order_by('-rating_score', '-pub_date')

    return snippet_list(
        request,
        queryset=snippet_qs,
        template_name='search/search.html',
        extra_context={'query': query},
    )


def autocomplete(request):
    q = request.GET.get('q', '')
    results = []
    if len(q) > 2:
        sqs = SearchQuerySet()
        result_set = sqs.filter(title_ngram=q)[:10]
        for obj in result_set:
            results.append({
                'title': obj.title,
                'author': obj.author,
                'url': obj.url
            })
    return HttpResponse(json.dumps(results), mimetype='application/json')


def tag_hint(request):
    q = request.GET.get('q', '')
    results = []
    if len(q) > 2:
        tag_qs = Tag.objects.filter(slug__startswith=q)
        annotated_qs = tag_qs.annotate(count=Count('taggit_taggeditem_items__id'))

        for obj in annotated_qs.order_by('-count', 'slug')[:10]:
            results.append({
                'tag': obj.slug,
                'count': obj.count,
            })

    return HttpResponse(json.dumps(results), mimetype='application/json')

wsgi/openshift/cab/templates/cab/add_snippet.html
{% extends "base_user.html" %}
{% load static from staticfiles %}

{% block title %}Add a snippet{% endblock %}

{% block content_header %}Add a snippet{% endblock %}
{% block extra_css %}
<link rel="stylesheet" href="{% static "css/autoSuggest.css" %}" />
<link rel="stylesheet" href="{% static "codemirror/lib/codemirror.css" %}" />
<link rel="stylesheet" href="{% static "codemirror/theme/ambiance.css" %}" />
<style type="text/css">
  .CodeMirror {
    border: 1px solid #eee;
    height: auto;
    min-height: 300px;
  font-size: 12px;
  }

  .CodeMirror-scroll {
    overflow-y: hidden;
    overflow-x: hidden;
  }
  .CodeMirror-hscrollbar {
    display: none;
  }
</style>
{% endblock extra_css %}

{% block extra_scripts %}
<script type="text/javascript" src="{% static "admin/js/jquery.js" %}"></script>
<script type="text/javascript" src="{% static "admin/js/jquery.init.js" %}"></script>
<script type="text/javascript" src="{% static "js/jquery.autoSuggest.js" %}"></script>
<script type="text/javascript" src="{% static "epiceditor/js/epiceditor.min.js" %}"></script>
<script type="text/javascript" src="{% static "codemirror/lib/codemirror.js" %}"></script>
<script type="text/javascript" src="{% static "codemirror/mode/haskell/haskell.js" %}"></script>
{% endblock %}
{% block content %}
  <p><span class="error"><strong>Please remember that this site is not a pastebin or debugging tool; it is intended for finished, working pieces of code.</strong></span> If you need someplace to temporarily post some code while others help you debug it, please use the pastebin at <a href="http://lpaste.net/">lpaste.net</a>.</p>

  {% if form.errors %}
    <p class="error">Please correct the errors below:</p>
  {% endif %}

  <form method="post" action="">{% csrf_token %}
    <dl>
      <dt><label for="id_title">Title: {% if form.title.errors %}<span class="error">{{ form.title.errors|join:", " }}</span>{% endif %}</label></dt>
      <dd>{{ form.title }}</dd>
      <dt><label for="id_tag_list">Tags: {% if form.tag_list.errors %}<span class="error">{{ form.tag_list.errors|join:", " }}</span>{% endif %} </label></dt>
      <dd>{{ form.tags }} <br />Use commas between tag names, and hyphens for multiple words, like "tag1, tag2, tag3-with-long-name"</dd>
      <dt><label for="id_code">Code: {% if form.code.errors %}<span class="error">{{ form.code.errors|join:", " }}</span>{% endif %}</label></dt>
      <dd>{{ form.code }}</dd>
      <dt><label for="id_description">Description: {% if form.description.errors %}<span class="error">{{ form.description.errors|join:", " }}</span>{% endif %}</label></dt>
      <dd>{{ form.description }}<br />
      You can use Markdown syntax here (see the sidebar), but <strong>raw HTML will be removed</strong>.</dd>
      <dt><button type="submit" value="Save">Save</button></dt>
    </dl>
  </form>
{% endblock %}

{% block sidebar %}
  <div class="panel">
  <p>All fields are required; tags should be separated with spaces, and you can use Markdown in the description for your snippet, but <strong>raw HTML will be removed</strong>.</p>
  </div>

  <div class="panel callout">
  <p><strong>Remember:</strong> by posting a snippet, you agree to let anyone make use of the code.</p>
  </div>

{% endblock %}

wsgi/openshift/cab/templates/cab/confirm_bookmark_delete.html
{% extends "base.html" %}

{% block content_header %}Delete bookmark?{% endblock %}

{% block content %}
<h3>{{ snippet.title }}</h3>

<form method="post" action=".">{% csrf_token %}
  <input type="submit" value="Delete" />
</form>
{% endblock %}

wsgi/openshift/cab/templates/cab/language_detail.html
{% extends "cab/snippet_list.html" %}
{% load static from staticfiles %}

{% block feeds %}<link rel="alternate" href="/feeds/language/{{ language.slug }}/" type="application/atom+xml" title="Feed of snippets written in {{ language.name }}" />{% endblock %}

{% block title %}All snippets written in {{ language.name }}{% if months %}, last {{ months }} months{% endif %}{% endblock %}

{% block content_header %}All snippets written in {{ language.name }}{% if months %}, last {{ months }} months{% endif %}{% endblock %}

{% block sidebar %}
  <p>{{ hits }} snippet{{ hits|pluralize }} {% ifequal hits 1 %}is{% else %}are{% endifequal %} written in {{ language.name }} so far.</p>
  <p><a rel="alternate" href="/feeds/language/{{ language.slug }}/" type="application/atom+xml"><img src="{% static "img/feed-icon-10x10.png" %}" alt="" /> Feed of snippets written in {{ language.name }}</a></p>
{% endblock %}

wsgi/openshift/cab/templates/cab/language_list.html
{% extends "base.html" %}
{% load core_tags %}

{% block title %}All languages{% endblock %}

{% block content_header %}All languages{% endblock %}

{% block content %}
  <ul>
  {% for language in object_list %}
    <li><a href="{{ language.get_absolute_url }}">{{ language.name }}</a></li>
  {% endfor %}
  </ul>

  <p class="pagination">{% if has_previous %}<a href="?page={{ previous }}">&lt; Previous {{ results_per_page }}</a>{% endif %}&nbsp;&nbsp;{% if has_next %}<a href="?page={{ next }}">Next {{ results_per_page }} &gt;</a>{% endif %}</p>

{% endblock %}

wsgi/openshift/cab/templates/cab/most_bookmarked.html
{% extends "cab/snippet_list.html" %}


{% block title %}Most-bookmarked snippets{% if months %} last {{ months }} months{% endif %}{% endblock %}

{% block content_header %}Most-bookmarked snippets{% if months %} last {{ months }} months{% endif %}{% endblock %}

{% block sidebar %}
  <p>You're looking at the most-bookmarked snippets on the site; {% if user.is_authenticated %}you can help useful snippets show up here by clicking the "bookmark this snippet" link on their pages and ading them to <a href="/bookmarks/">your bookmarks</a>{% else %}if you'd like to help useful snippets show up here, <a href="/accounts/register/">sign up for an account</a> and you'll get your own bookmarks list{% endif %}.</p>
{% endblock %}

wsgi/openshift/cab/templates/cab/snippet_detail.html
{% extends "base.html" %}
{% block extra_css %}
<link href='http://fonts.googleapis.com/css?family=Source+Code+Pro' rel='stylesheet' type='text/css'>
{% endblock extra_css %}
{% load cab_tags %}
{% load cache %}
{% load ratings_tags %}
{% load safe_markup %}
{% load url from future %}

{% block title %}{{ object.title }}{% endblock %}

{% block content_header %}{{ object.title }}{% endblock %}

{% block content %}
{{ object.highlighted_code|safe }}
<div>
{% if object|more_like_this %}
  <h3>More like this</h3>
  {% cache 600 mlt object.pk %}
  <ol>
    {% for related in object|more_like_this:5 %}
    <li><a href="{{ related.object.get_absolute_url }}">{{ related.object.title }}</a> by <a href="/users/{{ related.object.author.username }}/">{{ related.object.author.username }}</a>
      {{ related.object.pub_date|timesince }} ago
    </li>
    {% endfor %}
  </ol>
  {% endcache %}
{% endif %}

</div>
{% endblock %}

{% block sidebar %}
{{ object.description_html|safe }}

<dl>
  <dt>Author:</dt>
  <dd><a href="/users/{{ object.author.username }}/">{{ object.author.username }}</a></dd>
  <dt>Posted:</dt>
  <dd>{{ object.pub_date|date:"F j, Y" }}</dd>
  <dt>Tags:</dt>
  <dd>{% for tag in object.tags.all %}<a href="{% url "cab_snippet_matches_tag" tag.slug %}" class="radius secondary label">{{ tag.name }}</a> {% endfor %}</dd>
  <dt>Score:</dt>
  <dd>{{ object.rating_score }} (after {{ object.ratings.count }} rating{{ object.ratings.count|pluralize }})</dd>
</dl>

<h3>Tools</h3>
<ul>
  {% if user.is_authenticated %}
  {% ifequal user.id object.author.id %}
  <li><a href="/recipes/{{ object.id }}/edit/">Edit this recipe</a></li>
  {% endifequal %}
  {% if object|is_bookmarked:request.user %}
  <li>This recipe is in <a href="/bookmarks/">your bookmarks</a></li>
  {% else %}
  <li><a href="/bookmarks/add/{{ object.id }}/">Bookmark this recipe</a></li>
  {% endif %}
  {% with object|rating_score:request.user as rating_score %}
  {% if rating_score %}
  <li>You rated this recipe <strong>{% ifequal rating_score 1 %}useful{% else %}not useful{% endifequal %}</strong>.</li>
  {% else %}
  <li>Rate this recipe: <a href="/recipes/{{ object.id }}/rate/?score=up">useful</a> or <a href="/recipes/{{ object.id }}/rate/?score=down">not useful</a></li>
  {% endif %}
  {% endwith %}
  {% endif %}
  <li><a href="/recipes/{{ object.id }}/download/" type="{{ object.language.mime_type }}">Download this recipe</a></li>
  <li><a href="#comments">Comment on this recipe</a></li>
  {% if user.is_authenticated %}
  {% if not user|has_flagged:object %}
  <li>
    <form method="post" class="flag_form" action="{% url "cab_snippet_flag" object.id %}">{% csrf_token %}
      {{ flag_form.flag }}
      <button type="submit" class="small radius success" value="Flag">Flag</button>
    </form>
  </li>
  {% endif %}
  {% endif %}
</ul>
{% endblock %}

{% block extra_content %}
<div id="comments">
  <h2>Comments</h2>
  {% load comments %}
  {% get_comment_list for object as comment_list %}
  <dl>
    {% for comment in comment_list %}
    <dt id="c{{ comment.id }}"><a href="/users/{{ comment.user.username }}/">{{ comment.user.username }}</a> (on {{ comment.submit_date|date:"F j, Y" }}):</dt>
    <dd>{{ comment.comment|safe_markdown:"safe"|safe }}
      <p><a href="{{ comment.get_absolute_url }}">#</a></p></dd>
    {% endfor %}
  </dl>
  {% render_comment_form for object %}
</div>
{% endblock %}

wsgi/openshift/cab/templates/cab/tag_detail.html
{% extends "cab/snippet_list.html" %}
{% load static from staticfiles %}

{% block feeds %}<link rel="alternate" href="/feeds/tag/{{ tag.slug }}/" type="application/atom+xml" title="Feed of snippets tagged with '{{ tag.name }}'" />{% endblock %}

{% block title %}Tag "{{ tag.name }}"{% if months %}, last {{ months }} months{% endif %}{% endblock %}

{% block content_header %}Recipes tagged with "{{ tag.name }}"{% if months %}, last {{ months }} months{% endif %}{% endblock %}

{% block sidebar %}
  <p>{{ hits }} Recipe{{ hits|pluralize }} {% ifequal hits 1 %}is{% else %}are{% endifequal %} tagged with "{{ tag.name }}":</p>

  <p><a rel="alternate" href="/feeds/tag/{{ tag.slug }}/" type="application/atom+xml"><img src="{% static "img/rss.png" %}" alt="RSS" /> Feed of recipes tagged with '{{ tag.slug }}'</a></p>
{% endblock %}